version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin01
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
